# -*- coding: utf-8 -*-
"""S5_APP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jtj52ahNqUHmoA2yG4IUAwscV9aNpEz
"""

import numpy as np
import scipy.linalg as linalg
import scipy.signal as signal
import matplotlib.pyplot as plt

"""#Premiere Partie (LQR)

#Matrice d'état
"""

v_0 = 2 # m/s
theta_0 = 0 # rad
delta_0 = 0 # rad

A = 0.2*0.3
m = 5 # kg
Jm = 0.00005 # [kgm2]
r = 0.04 # [m]
N = 15.3
L = 0.3 # [m]
Km = 0.0028 # [Nm/A]
Rm = 0.64 # [ohms]
bm = 0.00001 # [Nms]
Cd = 0.5
rau = 1.225 # kg/m3


Jtot = Jm + m*r/N

speed_multiplier = -(Km**2*N/Rm + bm*N/r + rau*A*Cd*v_0*r/N)/Jtot

A = np.array([
    [speed_multiplier, 0 ,0],
    [0, 0 ,v_0],
    [0, 0 ,0]
])
B = np.array([
    [Km/(Jtot*Rm), 0],
    [0, 0],
    [0, v_0/L],
])
C = np.array([[1, 0, 0],
              [0, 1, 0]
])
D = np.array([[0, 0],
              [0, 0]
])

n = A.shape[0]  # Ordre du système

"""#Controllabilité et Observabilité"""

def ctrb(A, B):
    """Calcule la matrice de contrôlabilité Wc."""
    n = A.shape[0]
    Wc = B
    for i in range(1, n):
        Wc = np.hstack((Wc, np.linalg.matrix_power(A, i) @ B))
    return Wc

def obsv(A, C):
    """Calcule la matrice d'observabilité Wo."""
    n = A.shape[0]
    Wo = C
    for i in range(1, n):
        Wo = np.vstack((Wo, C @ np.linalg.matrix_power(A, i)))
    return Wo

Wc = ctrb(A, B)

rank_Wc = np.linalg.matrix_rank(Wc)
print(f"Matrice de contrôlabilité:\n{Wc}")
print(f"Rang de Wc (rank): {rank_Wc} -> {'Contrôlable' if rank_Wc == n else 'Non contrôlable'}\n")

Wo = obsv(A, C)

rank_Wo = np.linalg.matrix_rank(Wo)
print(f"Matrice d'observabilité:\n{Wo}")
print(f"Rang de Wo (rank): {rank_Wo} -> {'Observable' if rank_Wo == n else 'Non observable'}")

"""#LQR"""

# Matrices de pondération
Q = np.diag([100, 1, 1])  # Pénalité sur les états (v, y, theta) x'Qx
R = np.diag([1, 10])    # Pénalité sur la commande (V, delta) u'Ru

S = linalg.solve_continuous_are(A, B, Q, R)
print(f"Solution de Riccati S :\n{S}\n")

R_inv = linalg.inv(R)
K_lqr = R_inv @ B.T @ S
print(f"Gain LQR K_lqr:\n{K_lqr}\n")

"""#Poles"""

A_lqr = A - B @ K_lqr
poles_lqr = linalg.eigvals(A_lqr)
print(f"Pôles LQR en boucle fermée (eig(A-BK)):\n{poles_lqr}")

"""#2eme partie

"""

v_0 = 2 # m/s
theta_0 = 0 # rad
delta_0 = 0 # rad

m = 5 # kg
Jm = 0.00005 # [kgm2]
r = 0.04 # [m]
N = 15.3
L = 0.3 # [m]
Km = 0.0028 # [Nm/A]
Rm = 0.64 # [ohms]
bm = 0.00001 # [Nms]
Cd = 0.5
rau = 1.225 # kg/m3


Jtot = Jm + m*r/N

A_sta = np.array([
    [0, 0 ,0],
    [0, 0 ,v_0],
    [0, 0 ,0]
])
B_sta = np.array([
    [1, 0],
    [0, 0],
    [0, v_0/L],
])
C_sta = np.array([[0, 0, 0],
              [0, 1, 0]
])
D_sta = np.array([[1, 0],
              [0, 0]
])

n_sta = A_sta.shape[0]  # Ordre du système

Wc = ctrb(A_sta, B_sta)

rank_Wc = np.linalg.matrix_rank(Wc)
print(f"Matrice de contrôlabilité:\n{Wc}")
print(f"Rang de Wc (rank): {rank_Wc} -> {'Contrôlable' if rank_Wc == n_sta else 'Non contrôlable'}\n")

Wo = obsv(A_sta, C_sta)

rank_Wo = np.linalg.matrix_rank(Wo)
print(f"Matrice d'observabilité:\n{Wo}")
print(f"Rang de Wo (rank): {rank_Wo} -> {'Observable' if rank_Wo == n_sta else 'Non observable'}")

# Pôles désirés (plus rapides et plus amortis que les pôles BO)
poles_desires = np.array([-1.0 + 0.5j, -1.0 - 0.5j, -1])
print(f"Pôles désirés: {poles_desires}\n")

result = signal.place_poles(A_sta, B_sta, poles_desires)
K_sta = result.gain_matrix
print(f"Gain de retour d'état K (place):\n{K_sta}\n")

# Vérification
A_cl = A_sta - B_sta @ K_sta
poles_cl = linalg.eigvals(A_cl)
print(f"Pôles réels en boucle fermée (eig(A-BK)): {np.sort(poles_cl)}")

# Covariances des bruits
Qn = np.diag([0.1, 0.1, 0.1]) # Bruit de processus w
Rn = np.diag([0.1, 0.1])   # Bruit de mesure v

print(f"Covariance Qn (processus):\n{Qn}")
print(f"Covariance Rn (mesure):\n{Rn}\n")

# 1. Résoudre la CARE duale (transposer A et C)
# Note : A -> A.T, B -> C.T, Q -> Qn, R -> Rn
Pe = linalg.solve_continuous_are(A.T, C.T, Qn, Rn)
print(f"Covariance d'erreur Pe (P en MATLAB):\n{Pe}\n")

# 2. Calculer le gain L
Rn_inv = linalg.inv(Rn)
L_kalman = Pe @ C.T @ Rn_inv
print(f"Gain de Kalman L:\n{L_kalman}\n")

# Vérification des pôles de l'estimateur
A_est = A - L_kalman @ C
poles_est = linalg.eigvals(A_est)
print(f"Pôles de l'estimateur (eig(A-LC)):\n{poles_est}")